### ISSUE TITLE
amongus

### ISSUE THREAD

**Issue by BackupCup** [Clockwork-Interactive/RefractionAPI-MC#1]
ඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞඞ
![chrome_67lS8bHB7S](https://github.com/user-attachments/assets/a0f3855f-a51d-4862-b23e-07832dc427e4)

**Comment by BackupCup** [comment]
nvm fixed it

**Comment by ZeusIGN** [comment]
fixed in #afd7fdc
